services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:27.1
    command: "-fallbackfee=0.0002"
    volumes:
      - ./tmp/bitcoin:/srv/app/.bitcoin
  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.10.0
    volumes:
      - ./tmp/electrs:/srv/app/db
    ports:
      - 50001:50001
    depends_on:
      - bitcoind
  proxy:
    image: ghcr.io/rgb-tools/rgb-proxy-server:0.2.1
    ports:
      - 3000:3000
